spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:luxlog;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver
  data:
    web:
      pageable:
        default-page-size: 5
        one-indexed-parameters: true
  #embede 설정(자동으로 유저 데이터 넣기
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true # .sql 파일이 hibernate초기화 이후 동작 하도록
    hibernate:
      ddl-auto: create-drop