spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:luxlog;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver
  data:
    web:
      pageable:
        default-page-size: 5
        one-indexed-parameters: true
